name: 'Setup PHP + Cache and install Composer dependencies + Copy .env file'
description: 'Setup PHP + Cache and install Composer dependencies + Copy .env file'
runs:
  using: 'composite'
  steps:
    - uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
      with:
        php-version: '8.3'

    - name: 🔍 Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: 🗄️ Cache composer dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: 📦 Install dependencies
      run: composer install --no-interaction --prefer-dist
      shell: bash

    - name: 📋 Copy .env file
      run: cp .env.ci .env
      shell: bash
