name: 'Setup PHP + Cache and install Composer dependencies + Copy .env file'
description: 'Setup PHP + Cache and install Composer dependencies + Copy .env file'
runs:
  using: 'composite'
  steps:
    - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: '8.3'

    - name: 🔍 Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: 🗄️ Cache composer dependencies
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: 📦 Install dependencies
      run: composer install --no-interaction --prefer-dist
      shell: bash

    - name: 📋 Copy .env file
      run: cp .env.ci .env
      shell: bash
