name: Deploy to Live

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6
        with:
          run_install: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: 'pnpm'
      - name: 📦 Install  dependencies
        run: pnpm install
      - name: 📦 Build production bundle
        run: pnpm build
      - name: 📥 Commit and push local changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 💄Apply theme changes
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 🕹️ Executing remote SSH commands using password
      uses: appleboy/ssh-action@90162d1e4396c5c4b7671d60cae550a8b1ae1d0b # master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd einstein
          git pull
          php83 /usr/bin/composer install --no-dev -d ${PWD}
