name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: Static analysis
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: 📦 Setup PHP + install deps
        uses: ./.github/actions/setup-php-composer

      - name: 🔬 Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --error-format=github --memory-limit=512M
